version: '3.3'

services:
  nginx:
    image: nginx:1.29
    container_name: nginx
    ports:
      - "8081:8081"
      - "8087:8087"
    networks:
      - dbnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway
      - session

  rabbitmq:
    image: steelycop/rabbitmq:1.0
    container_name: rabbitmq
    environment:
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      SERVER_PORT: 5672
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dbnet

  postgres:
    image: steelycop/postgres:1.0
    container_name: psgr
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SERVER_PORT: 5432
    ports:
      - "5432:5432"
    networks:
      - dbnet

  session:
    image: steelycop/session:1.0
    container_name: session
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
      SERVER_PORT: 8081
    networks:
      - dbnet
    depends_on:
      - postgres
      - rabbitmq

  hotel:
    image: steelycop/hotel:1.0
    container_name: hotel
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotels_db
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    networks:
      - dbnet
    depends_on:
      - rabbitmq
      - session

  booking:
    image: steelycop/booking:1.0
    container_name: booking
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
      SERVER_PORT: 8083
    ports:
      - "8083:8083"
    networks:
      - dbnet
    depends_on:
      - postgres
      - rabbitmq

  payment:
    image: steelycop/payment:1.0
    container_name: payment
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
      SERVER_PORT: 8084
    ports:
      - "8084:8084"
    networks:
      - dbnet
    depends_on:
      - postgres
      - rabbitmq

  loyalty:
    image: steelycop/loyalty:1.0
    container_name: loyalty
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balances_db
      SERVER_PORT: 8085
    ports:
      - "8085:8085"
    networks:
      - dbnet
    depends_on:
      - postgres
      - rabbitmq

  report:
    image: steelycop/report:1.0
    container_name: report
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statistics_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      SERVER_PORT: 8086
    ports:
      - "8086:8086"
    networks:
      - dbnet
    depends_on:
      - postgres
      - rabbitmq
      - hotel
      - payment
      - loyalty

  gateway:
    image: steelycop/gateway:1.0
    container_name: gateway
    environment:
      SESSION_SERVICE_HOST: session
      SESSION_SERVICE_PORT: 8081
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      BOOKING_SERVICE_HOST: booking
      BOOKING_SERVICE_PORT: 8083
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
      REPORT_SERVICE_HOST: report
      REPORT_SERVICE_PORT: 8086
      SERVER_PORT: 8087
    networks:
      - dbnet
    depends_on:
      - session
      - hotel
      - booking
      - payment
      - loyalty
      - report

networks:
  dbnet:
    driver: bridge
