version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - dbnet

  postgres:
    image: postgres:service
    container_name: psgr
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - dbnet

  session:
    image: 2_session:service
    container_name: session
    environment:
      POSTGRES_HOST: psgr
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - dbnet
    depends_on:
      - rabbitmq

  hotel:
    image: 2_hotel:service
    container_name: hotel
    environment:
      POSTGRES_HOST: psgr
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotels_db
      SERVER_PORT: 8082
    networks:
      - dbnet
    depends_on:
      - rabbitmq
      - session

  payment:
    image: 2_payment:service
    container_name: payment
    environment:
      POSTGRES_HOST: psgr
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
      SERVER_PORT: 8084
    networks:
      - dbnet
    depends_on:
      - rabbitmq
      - session
      - hotel

  loyalty:
    image: 2_loyalty:service
    container_name: loyalty
    environment:
      POSTGRES_HOST: psgr
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balances_db
      SERVER_PORT: 8085
    networks:
      - dbnet
    depends_on:
      - rabbitmq
      - session
      - hotel
      - payment

  report:
    image: 2_report:service
    container_name: report
    environment:
      POSTGRES_HOST: psgr
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statistics_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      SERVER_PORT: 8086
    networks:
      - dbnet
    depends_on:
      - rabbitmq
      - session
      - hotel
      - payment
      - loyalty

  booking:
    image: 2_booking:service
    container_name: booking
    environment:
      POSTGRES_HOST: psgr
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
      SERVER_PORT: 8083
    networks:
      - dbnet
    depends_on:
      - rabbitmq
      - session
      - hotel
      - payment
      - loyalty
      - report

  gateway:
    image: 2_gateway:service
    container_name: gateway
    environment:
      SESSION_SERVICE_HOST: session
      SESSION_SERVICE_PORT: 8081
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      BOOKING_SERVICE_HOST: booking
      BOOKING_SERVICE_PORT: 8083
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
      REPORT_SERVICE_HOST: report
      REPORT_SERVICE_PORT: 8086
      SERVER_PORT: 8087
    ports:
      - "8087:8087"
    networks:
      - dbnet
    depends_on:
      - session
      - hotel
      - booking
      - payment
      - loyalty
      - report

networks:
  dbnet:
    driver: bridge
