services:
  nginx:      
    image: nginx:1.29
    deploy:
      placement:
        constraints:
          - node.role == manager
      replicas: 1
    ports:
      - "8081:8081"
      - "8087:8087"
    networks:
      - dbnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  rabbitmq:
    image: steelycop/rabbitmq:1.0
    environment:
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      SERVER_PORT: 5672
    deploy:
      replicas: 1
    networks:
      - dbnet

  postgres:
    image: steelycop/postgres:2.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SERVER_PORT: 5432
    deploy:
      replicas: 1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      dbnet:
        aliases:
          - psgr

  session:
    image: steelycop/session:2.0
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
      SERVER_PORT: 8081
    deploy:
      replicas: 1
    networks:
      - dbnet
    depends_on:
      - postgres
      - rabbitmq

  hotel:
    image: steelycop/hotel:2.0
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotels_db
      SERVER_PORT: 8082
    deploy:
      replicas: 1
    networks:
      - dbnet
    depends_on:
      - rabbitmq
      - session

  booking:
    image: steelycop/booking:2.0
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reservations_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
      SERVER_PORT: 8083
    deploy:
      replicas: 1
    networks:
      - dbnet
    depends_on:
      - postgres
      - rabbitmq
      - hotel
      - payment
      - loyalty

  payment:
    image: steelycop/payment:2.0
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payments_db
      SERVER_PORT: 8084
    deploy:
      replicas: 1
    networks:
      - dbnet
    depends_on:
      - postgres
      - rabbitmq

  loyalty:
    image: steelycop/loyalty:2.0
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balances_db
      SERVER_PORT: 8085
    deploy:
      replicas: 1
    networks:
      - dbnet
    depends_on:
      - postgres
      - rabbitmq

  report:
    image: steelycop/report:2.0
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: statistics_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      SERVER_PORT: 8086
    deploy:
      replicas: 1
    networks:
      - dbnet
    depends_on:
      - postgres
      - rabbitmq
      - hotel
      - payment
      - loyalty

  gateway:
    image: steelycop/gateway:2.0
    environment:
      SESSION_SERVICE_HOST: session
      SESSION_SERVICE_PORT: 8081
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      BOOKING_SERVICE_HOST: booking
      BOOKING_SERVICE_PORT: 8083
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
      REPORT_SERVICE_HOST: report
      REPORT_SERVICE_PORT: 8086
      SERVER_PORT: 8087
    deploy:
      replicas: 1
    networks:
      - dbnet
    depends_on:
      - session
      - hotel
      - booking
      - payment
      - loyalty
      - report

networks:
  dbnet:
    driver: overlay
